"""Add Router and PPP details to Customer

Revision ID: 3bc7315a738f
Revises: 42f99a906a8d
Create Date: 2026-07-17 01:59:08.632658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bc7315a738f'
down_revision: Union[str, None] = '42f99a906a8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('routers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('ip_address', sa.String(length=50), nullable=False),
    sa.Column('api_port', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('password_encrypted', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('last_connected', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_routers_name'), 'routers', ['name'], unique=True)
    op.add_column('customers', sa.Column('router_id', sa.String(length=36), nullable=True))
    op.add_column('customers', sa.Column('connection_type', sa.String(length=50), nullable=True))
    op.add_column('customers', sa.Column('ppp_username', sa.String(length=100), nullable=True))
    op.add_column('customers', sa.Column('ppp_password', sa.String(length=100), nullable=True))
    op.add_column('customers', sa.Column('hotspot_username', sa.String(length=100), nullable=True))
    op.add_column('customers', sa.Column('hotspot_password', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'hotspot_password')
    op.drop_column('customers', 'hotspot_username')
    op.drop_column('customers', 'ppp_password')
    op.drop_column('customers', 'ppp_username')
    op.drop_column('customers', 'connection_type')
    op.drop_column('customers', 'router_id')
    op.drop_index(op.f('ix_routers_name'), table_name='routers')
    op.drop_table('routers')
    # ### end Alembic commands ###
