"""Add IP and browser to activity logs

Revision ID: 42f99a906a8d
Revises: 5a0ac33f4902
Create Date: 2026-07-17 01:49:53.535195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42f99a906a8d'
down_revision: Union[str, None] = '5a0ac33f4902'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity_logs', sa.Column('ip_address', sa.String(length=50), nullable=True))
    op.add_column('activity_logs', sa.Column('browser', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activity_logs', 'browser')
    op.drop_column('activity_logs', 'ip_address')
    # ### end Alembic commands ###
