"""Add tenants table and tenant_id mapping columns

Revision ID: 6d8c4469e44a
Revises: 40249acf3607
Create Date: 2026-07-17 02:13:31.915713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d8c4469e44a'
down_revision: Union[str, None] = '40249acf3607'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('domain', sa.String(length=100), nullable=True),
    sa.Column('subscription_plan', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('logo_url', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenants_domain'), 'tenants', ['domain'], unique=True)
    op.create_index(op.f('ix_tenants_name'), 'tenants', ['name'], unique=True)
    op.add_column('customers', sa.Column('tenant_id', sa.String(length=36), nullable=True))
    op.add_column('routers', sa.Column('tenant_id', sa.String(length=36), nullable=True))
    op.add_column('users', sa.Column('tenant_id', sa.String(length=36), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'tenant_id')
    op.drop_column('routers', 'tenant_id')
    op.drop_column('customers', 'tenant_id')
    op.drop_index(op.f('ix_tenants_name'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_domain'), table_name='tenants')
    op.drop_table('tenants')
    # ### end Alembic commands ###
